name: Update Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2
      with:
        path: stats
        repository: GMahmoud/stats
        token: ${{ secrets.ACCESS_TOKEN }}
    
    # Push generated stats to GMahmoud
    - name: Get generated stats to profile repo
      run: |
        git config --global user.name "GMahmoud/GMahmoud"
        git config --global user.email "mahmoud.ghorbel@hotmail.com"  
        ls stats
        rm -rf generated
        cp -r $GITHUB_WORKSPACE/generated .
        git add .
        git commit -m 'Update generated files' || echo
        git push
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
